import assert from 'node:assert/strict';
import { mkdtemp, rm, readdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { DefaultResourceLoader, SettingsManager, createAgentSession, SessionManager } from '@earendil-works/pi-coding-agent';

process.env.PI_OFFLINE = '1';
process.env.PI_TELEMETRY = '0';
const temporary = await mkdtemp(join(tmpdir(), 'jevvy-pi-'));
process.env.JEVVY_STORAGE_DIR = join(temporary, 'results');
const cwd = process.cwd(), agentDir = join(temporary, 'agent');
const settingsManager = SettingsManager.inMemory();
const loader = new DefaultResourceLoader({ cwd, agentDir, settingsManager, additionalExtensionPaths: [resolve(process.env.JEVVY_EXTENSION ?? 'dist/extension.js')], noExtensions: true, noSkills: true, noPromptTemplates: true, noThemes: true, noContextFiles: true });
let session;
try {
  await loader.reload();
  assert.deepEqual(loader.getExtensions().errors, []);
  ({ session } = await createAgentSession({ cwd, agentDir, settingsManager, resourceLoader: loader, sessionManager: SessionManager.inMemory(cwd), tools: ['jevvy_comments', 'jevvy_results'] }));
  const getTool = name => { const t = session.agent.state.tools.find(t => t.name === name); assert.ok(t, `Missing ${name}`); return t; };
  const scan = await getTool('jevvy_comments').execute('scan', { mode: 'files', files: ['fixtures/comments.ts', 'fixtures/comments.py', 'fixtures/comments.rs', 'fixtures/comments.sol', 'fixtures/Card.tsx'], dryRun: !process.argv.includes('--live') }, new AbortController().signal);
  assert.ok(scan.details.bundleId);
  assert.ok(!scan.isError);
  const bundle = JSON.parse(await readFile(scan.details.path, 'utf8'));
  assert.equal(bundle.run.status, 'completed');
  assert.equal(bundle.coverage.units.selected, 14);
  assert.equal(bundle.coverage.files.filter(file => file.status === 'parsed').length, 5);
  assert.equal(bundle.coverage.labels.error, 0);
  assert.equal(bundle.coverage.labels[process.argv.includes('--live') ? 'ok' : 'not_evaluated'], 196);
  assert.match(scan.content[0].text, /selected/);
  assert.ok(scan.details.cursor);
  const overview = await getTool('jevvy_results').execute('overview', { bundleId: scan.details.bundleId, view: 'overview' }, new AbortController().signal);
  assert.match(overview.content[0].text, /writing_clarity/);
  const context = await getTool('jevvy_results').execute('context', { bundleId: scan.details.bundleId, view: 'context', limit: 1 }, new AbortController().signal);
  assert.match(context.content[0].text, /returned=1/);
  const before = (await readdir(join(process.env.JEVVY_STORAGE_DIR, 'bundles'))).length;
  await session.prompt('/jevvy comments --files fixtures/comments.ts --dry-run');
  const after = (await readdir(join(process.env.JEVVY_STORAGE_DIR, 'bundles'))).length;
  assert.equal(after, before + 1);
  assert.ok(session.messages.some(m => m.role === 'custom' && m.customType === 'jevvy-results'));
  const previousTool = getTool('jevvy_comments');
  await session.reload();
  assert.deepEqual(loader.getExtensions().errors, []);
  assert.notEqual(getTool('jevvy_comments'), previousTool);
  const reloaded = await getTool('jevvy_comments').execute('after-reload', { mode: 'files', files: ['fixtures/comments.sol'], dryRun: true }, new AbortController().signal);
  const reloadedBundle = JSON.parse(await readFile(reloaded.details.path, 'utf8'));
  assert.equal(reloadedBundle.run.status, 'completed');
  assert.ok(reloadedBundle.units.length > 0);
  assert.equal(reloadedBundle.coverage.files[0].status, 'parsed');
  console.log(JSON.stringify({ pi: '0.86.1', platform: `${process.platform}-${process.arch}`, loaded: true, command: true, tools: true, modelVisibleContent: true, pagination: true, context: true, reload: true, live: process.argv.includes('--live'), coverage: bundle.coverage, bundleId: scan.details.bundleId }));
} finally { session?.dispose(); await rm(temporary, { recursive: true, force: true }); }
